_commit: v0.3.1
_src_path: https://github.com/gabriel-andreescu/BethesdaModKit.git
author: GabonZ
bmk_repository: https://github.com/gabriel-andreescu/BethesdaModKit.git
components:
  - native
description: Cancel melee attacks and transition into a block with one press.
devbench_api: false
devbench_tests: false
game: skyrim
mcm: true
mutagen_source: src/mutagen/CancelAttackSKSE
native_settings: true
native_source: src/native
pack_assets: false
papyrus_source: src/papyrus
pre_commit: true
project_name: CancelAttackSKSE
